### ISSUE TITLE
Release v0.1.1 includes APK v0.1.0

### ISSUE THREAD

**Issue by tadwohlrapp** [DanielRendox/RoutineTracker#11]
As the title states. The APK in the current release 0.1.1 shows up as version 0.1.0

Obtanium gets confused as it tries updating the installed 0.1.0 to 0.1.1 but keeps downloading and installing 0.1.0 over and over again, haha

**Comment by DanielRendox** [comment]
Yeah, I messed up with this. Didn't expect it to cause problems. Thanks for letting me know! 

I created another realease v0.1.0 with the same APK and deleted the previous one entirely, including the tag v0.1.1. Please, check if the issue is fixed.
