### ISSUE TITLE
Brainstorming ideas

### ISSUE THREAD

**Issue by warmachinesocial** [DanielRendox/RoutineTracker#14]
@DanielRendox crazy work man.. I'm here to learn composeUI and android in kotlin... 

Well there are many apps like i have used habit tracker however the point of all them they miss out is how easily can we make someone record or track and save their activities. 

If we want a user to track his routine we also need to "force" user to follow it, that's just in my view. I have tried using apps where i want to keep following my routine to make it into habit but end up deleting because I have to open the app and record.

We could come up with something like wake up & sleeping time and user enters the time. Reminds about this routine may be after or before 5min? And shows up in notification on when he/she is using the phone.

Rest is same for all user defined routines. However we need to implement the time feature, i don't know if this is how you see it..

All I'm saying is make user busy by timing such that he/she follows the routine and same time we track.

Open to your suggestions/opinions

**Comment by DanielRendox** [comment]
Hey, thank you for the suggestions! Yeah, I faced this myself and tried many habit-tracking apps to stick to my goals. Unfortunately, what I found out is that unless we become more organized and force ourselves to complete planned activities, no app can help us do that. These apps are good at automating the planning process, tracking our progress, and displaying the results in a visually appealing form. However, I'll do my best to make the app as helpful as possible and I do plan to integrate reminders.
