### ISSUE TITLE
Add to Fdroid

### ISSUE THREAD

**Issue by Thewisem** [DanielRendox/RoutineTracker#16]
Fdroid is an open aource app store designed for open source enthusiast and it would be a great addition to the app store.

**Comment by DanielRendox** [comment]
Hey, thanks for the suggestion! I do plan to add Routine Tracker to several Android app stores later. But first, let me find time to take it beyond MVP 😅

**Comment by Thewisem** [comment]
Thank you for adding it in IzzyonDroid repo. If it is possible, could you add it to official fdroid repo as well. Thanks for the great app

**Comment by vdbhb59** [comment]
Hey mate, just wanted to ask, if it is possible to add to F-Droid (via reproducible builds) or would you be adding it there yourself?
