### ISSUE TITLE
Please move Tick mark position

### ISSUE THREAD

**Issue by iBabu007** [DanielRendox/RoutineTracker#8]
Please if possible then move Tick mark position to the right side 
or single tap (whole area) to tick.
And long press to habit calendar/edit habit.

**Comment by DanielRendox** [comment]
Hi, thanks for your suggestion. I understand what you are talking about.

I intended to make the UI similar to how it is in many other to-do apps. The tick mark is on the left, tapping the whole area opens the details, and checking the tick mark (un)completes the habit. It seems more intuitive to me. However, we can consider adding a customization option for this later in the settings. Closing, for now.

To everyone reading this, please use [GitHub discussions](https://github.com/DanielRendox/RoutineTracker/discussions) for such suggestions and feature requests.
